WebApplication1/Controllers/SubmissionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Castle.Core.Internal;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using WebApplication1.Models;
using WebApplication1.Utility;

namespace WebApplication1.Controllers
{
	[Authorize]
	public class SubmissionsController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly ISubmissionService _submissionService;
		private readonly IWebHostEnvironment _host;
		private readonly ILogger<SubmissionsController> _logger;
		public SubmissionsController(ISubmissionService submissionService, UserManager<ApplicationUser> userManager, IWebHostEnvironment host, ILogger<SubmissionsController> logger)
		{
			_logger = logger;
			_host = host;
			_submissionService = submissionService;
			_userManager = userManager;
		}

		[Authorize(Roles = "Teacher")]
		public IActionResult Index()
		{
			var list = _submissionService.GetSubmissions();
			return View(list);
		}

		[HttpGet]
		public IActionResult Details(string taskId, string email)
		{

			if (taskId.IsNullOrEmpty() == false)
			{
				try
				{
					var submission = _submissionService.GetSubmission(Guid.Parse(Encryption.SymmetricDecrypt(taskId)), Encryption.SymmetricDecrypt(email));
					ViewBag.taskId = taskId;
					ViewBag.Copied = true;
					if (submission != null) {
						IEnumerable<SubmissionViewModel> copies = _submissionService.GetSubmissions().Where(x => x.Hash == submission.Hash);
						if (copies.Count() > 1)
						{
							ViewBag.Copied = false;
						} 
					}
					//submission.TaskId = Guid.Parse(Encryption.SymmetricDecrypt(taskId));
					return View(submission);
				}
				catch (Exception e) {
					return Redirect("/Home/Index");
				}
			}
			else
			{
				return Redirect("/Home/Index");
			}
		}

		[HttpPost]
		public async Task<IActionResult> DetailsAsync(IFormFile file, String taskId,SubmissionViewModel data)
		{
			try
			{
				data.TaskId = Guid.Parse(Encryption.SymmetricDecrypt(taskId));
				data.UploaderEmail = User.Identity.Name;
				data.DateUploaded = DateTime.Now;
				if (file != null)
				{
					if (System.IO.Path.GetExtension(file.FileName) == ".pdf" && file.Length < 1048576)
					{
						//FF D8 >>>>> 255 216
						string uniqueFilename;
						//byte[] whitelist = new byte[] { 255, 216 };
						byte[] whitelist = new byte[] { 37, 80 };

						if (file != null)
						{
							MemoryStream userFile = new MemoryStream();

							using (var f = file.OpenReadStream())
							{
								byte[] buffer = new byte[2];
								f.Read(buffer, 0, 2);
								for (int i = 0; i < whitelist.Length; i++)
								{
									if (whitelist[i] == buffer[i])
									{ }
									else
									{
										TempData["Error"] = "Task Not Submitted";
										ModelState.AddModelError("file", "File Not Valid");
										return View();
									}
								}

								f.CopyTo(userFile);

								string hash = Encryption.Hash(userFile.ToString());

								f.Position = 0;

								uniqueFilename = Guid.NewGuid() + Path.GetExtension(file.FileName);
								data.FilePath = uniqueFilename;
								string absolutePath = _host.WebRootPath + @"\submissions\" + uniqueFilename;
								try
								{
									using (FileStream fsOut = new FileStream(absolutePath, FileMode.CreateNew, FileAccess.Write))
									{
										
										f.CopyTo(fsOut);
									}
									f.Close();

									

									file.CopyTo(userFile);
									data.Hash = hash;

									ApplicationUser user = await _userManager.FindByEmailAsync(User.Identity.Name);
									data.Signature = Encryption.SignData(userFile, user.PrivateKey);

									TempData["message"] = "Task Submitted Successfully";
									_submissionService.AddSubmission(data);
								}
								catch (Exception ex)
								{
									TempData["error"] = "Error Uploading File";
									_logger.LogError(ex, "Error While Saving File");
									return View("Error", new ErrorViewModel() { Message = "Error While Saving File. Try Again Later" + ex });
								}
							}

						}
					}
				}

				return Redirect("/Tasks/Index");
			}
			catch (Exception e)
			{
				TempData["error"] = "Task Not Submitted";
				return Redirect("/Tasks/Index");
			}
		}

		public IActionResult Download(string submissionId) {
			try
			{
				string sub = "";
				if (submissionId.IsNullOrEmpty() == false)
				{
					sub = Encryption.SymmetricDecrypt(submissionId);
				}
				var submission = _submissionService.GetSubmission(Guid.Parse(sub));

				return File(System.IO.File.OpenRead(_host.WebRootPath + @"\submissions\" + submission.FilePath), "application/pdf");
			}
			catch (Exception e) {
				TempData["error"] = "Error Downloading File";
				_logger.LogError("ERROR Downloading File: "+ e);
				return Redirect("/Tasks/Index");
			}
		}
	}
}

WebApplication1/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using WebApplication1.Utility;

namespace WebApplication1.Controllers
{
    public class TasksController : Controller
	{
        private readonly ITaskService _taskService;
        private readonly IWebHostEnvironment _host;
        private readonly ILogger<TasksController> _logger;
        public TasksController(ITaskService taskService, IWebHostEnvironment host, ILogger<TasksController> logger)
        {
            _logger = logger;
            _host = host;
            _taskService = taskService;
        }

        public IActionResult Index()
        {
            var list = _taskService.GetTasks();
            return View(list);
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        { return View(); }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(TaskViewModel data)
        {
            data.TaskName = HtmlEncoder.Default.Encode(data.TaskName);
            data.Deadline = data.Deadline; 
            data.TeacherEmail = User.Identity.Name;

            if (ModelState.IsValid)
            {
                if (data.Deadline > DateTime.Now)
                {
                    _taskService.AddTask(data);

                    TempData["message"] = "Task Created Successfully";
                    return View();
                }
                else {
                    TempData["error"] = "Deadline cant be in the past";
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", "Check your input. Operation failed");
                return View(data);
            }
        }

        public IActionResult Task()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Task(string taskId, string userName)
        {
            String taskIdentity = Encryption.SymmetricDecrypt(taskId);
            String userEmail = Encryption.SymmetricDecrypt(userName);

            return View();
        }

        [Authorize(Roles = "Teacher")]
        public IActionResult SubmittedTask()
        {
            return View();
        }

        public IActionResult SubmittedTasks() {
            var list = _taskService.GetTasks();
            return View(list);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Task Submission</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task Dashboard</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Homepage</a>
						</li>

					@if (SignInManager.IsSignedIn(User))
					{

					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a>
					</li>
						@if (User.IsInRole("Teacher"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Submissions" asp-action="Index">Submissions</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Create">Create Task</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/AddStudent">Add Student</a>
							</li>
						}
					}

					</ul>
				</div>
			</div>
		</nav>
	</header>



	<div class="container">
		@if (TempData["message"] != null)
		{
<div class="alert alert-primary" role="alert">
	@TempData["message"]
</div>}

		@if (TempData["error"] != null)
		{
<div class="alert alert-danger" role="alert">
	@TempData["error"]
</div>}

		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2021 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>